# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ManualBuild

on:
  workflow_dispatch:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./build/remix-comp-base.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  #BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Release, Debug]
        platform: [Win32]
        include:
          - zip_name: Wolf2009.zip
            bin_name: Release
            config: Release
            platform: Win32
          - zip_name: Wolf2009_Debug.zip
            bin_name: Debug
            config: Debug
            platform: Win32

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        ./generate-buildfiles_vs22.bat
        nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild /m /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}
        XCOPY /E /I /Y .\assets\ .\build\bin\${{matrix.bin_name}}\

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.zip_name}}
        path: ./build/bin/${{matrix.bin_name}}/*
        include-hidden-files: true